package codegen

import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.TypeSpec
import lexicon.LexiconDoc
import lexicon.LexiconProcedure
import lexicon.LexiconQuery
import lexicon.SchemaDef
import java.nio.file.Path
import java.util.*
import kotlin.io.path.Path

fun String.capitalize(): String {
    return this.replaceFirstChar {
        if (it.isLowerCase()) it.titlecase(Locale.getDefault()) else it.toString()
    }
}

fun SchemaDef.codegen(name: String): List<TypeSpec> {
    return when (this) {
        is LexiconProcedure -> this.codegen(name)
        is LexiconQuery -> this.codegen(name)
        // TODO object, query, record, subscription...
        else -> emptyList()
    }
}

fun LexiconDoc.codegen(destination: Path) {
    var description: String? = null
    val rootName = this.id.split(".").last().capitalize()
    val specs = mutableListOf<TypeSpec>()
    println("rootName: $rootName")

    this.defs.forEach { (name, def) ->
        specs += def.codegen(if (name == "main") rootName else "$rootName${name.capitalize()}")
        if (name == "main") description = def.description
    }

    if (specs.isNotEmpty()) {
        // TODO FileSpec package name
        val file = FileSpec.builder("", rootName)
            .addFileComment("""
This file was generated by Panorama. DO NOT EDIT.

Lexicon: ${this.id}
${description?.let { "Description: $it" }}
                        """.trimIndent())
        // TODO build dirs to match package name
        specs.forEach { file.addType(it) }
        file.build().writeTo(destination)
    }
}