package codegen.converters

import lexicon.LexiconDoc
import lexicon.LexiconNull
import kotlin.test.Test
import kotlin.test.assertEquals

class ExtTest {

    @Test
    fun `convertToFile format ok`() {
        assertEquals("""
        |// This file was generated by Panorama. DO NOT EDIT.
        |//
        |// Lexicon: foo.bar.runTest
        |// Version: 1
        |// Revision: N/A
        |// Description: N/A
        |//
        |package foo.bar
        |
        |public class TODO
        |
        """.trimMargin(),
            LexiconDoc(
                defs = mapOf("foo" to LexiconNull()),
                id = "foo.bar.runTest",
                lexicon = 1
            ).convertToFile().toString()
        )
    }

    @Test
    fun `camelToEnumCase ok`() {
        assertEquals("FOO_BAR", "fooBar".camelToEnumCase())
    }

    @Test
    fun `capitalize first char lowercase`() {
        assertEquals("Foobar", "foobar".capitalize())
    }

    @Test
    fun `capitalize first char uppercase`() {
        assertEquals("Foobar", "Foobar".capitalize())
    }


    @Test
    fun `uncapitalize first char lowercase`() {
        assertEquals("foobar", "foobar".uncapitalize())
    }

    @Test
    fun `uncapitalize first char uppercase`() {
        assertEquals("foobar", "Foobar".uncapitalize())
    }
}